"""移除驗證碼欄位

Revision ID: 3d62f7cf5ff7
Revises: ccca83ef3b35
Create Date: 2025-03-24 14:05:47.031048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d62f7cf5ff7'
down_revision = 'ccca83ef3b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expires')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
