"""Change email to phone for user verification

Revision ID: 7ff27c221dc5
Revises: 8387588f17b1
Create Date: 2025-03-25 08:54:02.188872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff27c221dc5'
down_revision = '8387588f17b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
