"""添加驗證碼字段到用戶模型

Revision ID: 8387588f17b1
Revises: 3d62f7cf5ff7
Create Date: 2025-03-24 14:29:37.899569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8387588f17b1'
down_revision = '3d62f7cf5ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expires')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
